### ISSUE TITLE
GT Guidelines and OCR-D Wiki

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd-website#294]
For questions, the GT guidelines are sometimes quite rigid. A link between the OCR-D Wiki and the Guidelines would be welcome.

# Steps

* [x] Development of a mechanism for the transfer of GT Wiki contributions to the GT Guidelines
* [x] Development and documentation as well as provision of a template for a GT Wiki submission
* [ ] put it on the website

**Comment by kba** [comment]
Duplicate of #226
